// Code generated by hertztool.

package main

import (
	"code.byted.org/middleware/hertz/byted"
	"code.byted.org/middleware/hertz_ext/v2/binding"
)

func main() {
	//hertz.Init()
	//r := app.Default()
	//
	//register(r)
	//r.Spin()

	binding.UseGJSONUnmarshaler()

	byted.Init()
	r := byted.Default()
	register(r)
	r.Spin()
}
